apiVersion: v1
kind: Namespace
metadata:
 name: gke-managed-filestorecsi

---
##### Lock release controller Service Account, Roles, RoleBindings
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filestore-lockrelease-controller-sa
  namespace: gcp-filestore-csi-driver
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: filestorecsi-node-driver-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: filestorecsi-node-driver-role
 namespace: gke-managed-filestorecsi
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "update", "create"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filestorecsi-node-leaderelection-role
  namespace: gke-managed-filestorecsi
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "delete", "update", "create"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: filestorecsi-lockrelease-controller-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: filestore-lockrelease-controller-sa
  namespace: gcp-filestore-csi-driver
roleRef:
 kind: ClusterRole
 name: filestorecsi-node-driver-cluster-role
 apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filestorecsi-node-leaderelection-binding
  namespace: gke-managed-filestorecsi
subjects:
- kind: ServiceAccount
  name: filestore-lockrelease-controller-sa
  namespace: gcp-filestore-csi-driver
roleRef:
  kind: Role
  name: filestorecsi-node-leaderelection-role
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: filestorecsi-node-driver-role-binding
 namespace: gke-managed-filestorecsi
subjects:
- kind: ServiceAccount
  name: gcp-filestore-csi-node-sa
  namespace: gcp-filestore-csi-driver
- kind: ServiceAccount
  name: filestore-lockrelease-controller-sa
  namespace: gcp-filestore-csi-driver
roleRef:
 kind: Role
 name: filestorecsi-node-driver-role
 apiGroup: rbac.authorization.k8s.io
