apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestore-lock-release-controller
  namespace: gcp-filestore-csi-driver
  labels:
    k8s-app: filestore-lock-release-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: filestore-lock-release-controller
  template:
    metadata:
      labels:
        k8s-app: filestore-lock-release-controller
        component: filestorecsi
    spec:
      priorityClassName: csi-gcp-fs-node
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: filestore-lock-release-controller
        image: registry.k8s.io/sig-storage/filestore-lockrelease-controller
        args:
        - --v=6
        resources:                                               
          requests:                                              
            cpu: 5m                                              
            memory: 10Mi                                         
      serviceAccountName: filestore-lockrelease-controller-sa
      tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
